all:
  children:
    dev:
      hosts:
        dev-build.home.prettybaked.com:
          ansible_ssh_host: 10.0.10.148
    prod:
      hosts:
    foreman:
      children:
        dev:
        prod:
    awx:
      children:
        dev:
        prod:
