all:
  children:
    dev:
      hosts:
        testvm1.home.prettybaked.com:
          ansible_ssh_host: 10.0.10.141
    prod:
    foreman:
      hosts:
        testvm1.home.prettybaked.com:
    awx:
      hosts:
        testvm1.home.prettybaked.com:
    buildservices:
      children:
        foreman:
        awx:
