all:
  children:
    foreman:
      hosts:
        buildservices01.home.prettybaked.com:
          ansible_ssh_host: 10.0.10.25
        build.home.prettybaked.com:
          ansible_ssh_host: 10.0.10.155
        build.dev.home.prettybaked.com:
          ansible_ssh_host: 10.0.100.25
    awx:
      hosts:
        buildservices01.home.prettybaked.com:
        build.home.prettybaked.com:
        build.dev.home.prettybaked.com:
    ldap:
      children:
        foreman:
        awx:

dev:
  hosts:
    build.home.prettybaked.com:
      ansible_ssh_host: 10.0.10.155
    build.devhome.prettybaked.com:
      ansible_ssh_host: 10.0.100.25
prod:
  hosts:
    buildservices01.home.prettybaked.com:
      ansible_ssh_host: 10.0.10.25