all:
  children:
    foreman:
      hosts:
        build.dev.home.prettybaked.com:
        dev-build.home.prettybaked.com:
    awx:
      hosts:
        build.dev.home.prettybaked.com:
        dev-build.home.prettybaked.com:

dev:
  hosts:
    build.dev.home.prettybaked.com:
      ansible_ssh_host: 10.0.10.155
prod:
  hosts:
    buildservices01.home.prettybaked.com:
      ansible_ssh_host: 10.0.10.25