all:
  children:
    dev:
      hosts:
        testvm1.home.prettybaked.com:
    prod:
    foreman:
      hosts:
        testvm1.home.prettybaked.com:
    awx:
      hosts:
        testvm1.home.prettybaked.com:
    buildservices:
      children:
        foreman:
        awx:
