all:
  children:
    foreman:
      hosts:
        build.home.prettybaked.com:
          ansible_ssh_host: 10.0.10.155
        dev-build.home.prettybaked.com:
          ansible_ssh_host: 10.0.100.25
    awx:
      hosts:
        build.dev.home.prettybaked.com:
        dev-build.home.prettybaked.com:
    ldap:
      children:
        foreman:
        awx:

dev:
  hosts:
    build.dev.home.prettybaked.com:
      ansible_ssh_host: 10.0.10.155
prod:
  hosts:
    buildservices01.home.prettybaked.com:
      ansible_ssh_host: 10.0.10.25