all:
  children:
    dev:
      hosts:
        testvm1.home.prettybaked.com:
          ansible_ssh_host: 10.0.10.143
    prod:
      hosts:
    foreman:
      children:
        dev:
    awx:
      children:
        dev:
