all:
  children:
    foreman:
      hosts:
        buildservices01.home.prettybaked.com:
        dev-build.home.prettybaked.com:
    awx:
      hosts:
        buildservices01.home.prettybaked.com:
        dev-build.home.prettybaked.com:

dev:
  hosts:
    dev-build.home.prettybaked.com:
      ansible_ssh_host: 10.0.10.151
prod:
  hosts:
    buildservices01.home.prettybaked.com:
      ansible_ssh_host: 10.0.10.25