all:
  children:
    dev:
      hosts:
        testvm1.home.prettybaked.com:
        test-build.home.prettybaked.com:
    prod:
      hosts:
    foreman:
      children:
        dev:
    awx:
      children:
        dev:
