all:
  children:
    dev:
      hosts:
        dev-build.home.prettybaked.com:
    prod:
      hosts:
    foreman:
      children:
        dev:
        prod:
    awx:
      children:
        dev:
        prod:
