---

foreman_repositories_version: "3.2"
foreman_installer_scenario: foreman
foreman_puppet_repositories_version: 7
foreman_server_url: 'https://testvm1.home.prettybaked.com'
foreman_validate_certs: false
foreman_username: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64386661616265363933633363626539653839313038356135376662393937636633303032366433
          3432656437373138643737643564366461346666316639360a646132326135353033393435356364
          31343232306263613832363737346230333862366362643238666363343031376163336263303738
          3937613630666565380a346465326132613463356138643931393665303533333762633830373965
          3433
foreman_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66323832646361653365373162666630636433363732333337656663333938613464393838633734
          6263646363623731356133653332363739396534373065630a303532623266623364383461633739
          33663365376663643832343062343362643831623437323765623733373732323137363530656432
          6138346435636264620a613863333764643130356232343339646663356236633862353332383335
          39396231653236373731623330343062356463346462316634326334333836303635
foreman_options:
  - enable-foreman-cli-ansible
  - enable-foreman-cli-discovery
  - enable-foreman-compute-libvirt
  - enable-foreman-plugin-ansible
  - enable-foreman-proxy-plugin-ansible
  - enable-foreman-proxy-plugin-discovery
  - 'foreman-initial-admin-username={{ foreman_username }}'
  - 'foreman-initial-admin-password={{ foreman_password }}'

foreman_organization: Default Organization
foreman_location: Default Location

foreman_ldap_auth_source_name: PrettyBaked-LDAP

foreman_auth_sources_ldap:
  - name: '{{ foreman_ldap_auth_source_name }}'
    host: '{{ ldap_authentication.host }}'
    port: 389
    tls: false
    onthefly_register: true
    server_type: posix
    account: '{{ ldap_authentication.account }}'
    account_password: '{{ ldap_authentication.account_password}}'
    base_dn: '{{ ldap_authentication.base_dn }}'
    groups_base: '{{ ldap_authentication.groups_base }}'
    attr_login: '{{ ldap_authentication.attr_login }}'
    attr_firstname: '{{ ldap_authentication.attr_firstname }}'
    attr_lastname: '{{ ldap_authentication.attr_lastname }}'
    attr_mail: '{{ ldap_authentication.attr_mail }}'
    ldap_filter: (&(objectClass=posixAccount)(|(gidNumber=1042)(gidNumber=2002)))
    locations: '{{ foreman_location }}'
    usergroup_sync: true

foreman_usergroups:
  internal:
    - name: administrators
      admin: yes
    - name: managers
      admin: no
      roles:
        - Manager
  external:
    - name: admin
      auth_source: '{{ foreman_ldap_auth_source_name }}'
      usergroup: administrators
    - name: users
      auth_source: '{{ foreman_ldap_auth_source_name }}'
      usergroup: managers

foreman_settings:
#  - name: host_owner
#    value: '{{ foreman_admin_id }}'
#  - name: ansible_ssh_private_key_file
#    value: '{{ foreman_proxy_user_homedir }}/.ssh/id_rsa'
  - name: entries_per_page
    value: 20
  - name: use_shortname_for_vms
    value: true
  - name: idle_timeout
    value: 480
  - name: destroy_vm_on_host_delete
    value: true

foreman_organizations:
  - name: '{{ foreman_organization }}'
    locations:
      - name: '{{ foreman_location}}'