---

foreman_repositories_version: "3.2"
foreman_installer_scenario: foreman
foreman_puppet_repositories_version: 7

foreman_organization: Default Organization
foreman_location: Default Location
foreman_domain: dev.home.prettybaked.com
foreman_prod_domain: home.prettybaked.com
foreman_tftp_root: /var/lib/tftpboot
foreman_ldap_auth_source_name: PrettyBaked-LDAP

foreman_options:
  - enable-foreman-cli-discovery
  - enable-foreman-compute-libvirt
  - enable-foreman-plugin-discovery
  - enable-foreman-proxy-plugin-discovery
  - foreman-proxy-plugin-discovery-install-images=true
  - enable-foreman-plugin-remote-execution
  - enable-foreman-proxy
  - foreman-proxy-tftp=true
  - "foreman-proxy-tftp-root={{ foreman_tftp_root }}"
  - foreman-proxy-httpboot=true
  - foreman-proxy-httpboot-listen-on=http
  - foreman-foreman-url=https://10.0.100.25
  - foreman-websockets-encrypt=false
  - foreman-proxy-bind-host=0.0.0.0
  - foreman-proxy-ssl=true
  - "foreman-proxy-foreman-base-url=https://10.0.100.25"
  - 'foreman-initial-admin-username={{ foreman_username }}'
  - 'foreman-initial-admin-password={{ foreman_password }}'

foreman_ssh_public_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          37363766333761326630633834666335336433356639633134343062393265663036666562666539
          3733613336623230303137303032666665623531303830390a386536626664336261633662353736
          62313134316535316365656431616462393062666261306561623935653334613261303634373132
          3230333064656435660a653831306237353764656636316562306534386465653465356333346265
          39343435376338623935363662343036656466623232386364373232656339626531643039303236
          34646431393563653832303337303236386662323330333132326261353238656238343730326630
          32616232363239323237626162386361386661393061613264613638343966623338656138393738
          37613938323436323239646663656130346366656239316233356561303839383932643162323865
          30646361386464303230663463393961346537343133373631356566303039643565646439643030
          35663237343637336534613965653565636336663563653433313634633330383734636635613938
          61316665383934363130666338366166343564623433383237643138303761633330303339633139
          39646239343536643834346166323032343663326565663235326335636135313937386335323133
          37323061626665663432383936636665653466306561343366386230663762356362396438613635
          38303931623036333132313432356539623937336663633161303735353730653765356462316334
          39386163333430613132313361366662646266373431323061303334636430303636323066643938
          61353532396532323861393039366363383466623035386530643536376463353437396432633263
          61316230396633336463623836356333656365323730393264613737313336333036656337316132
          32303065383332373462363365373764373764366239336133626265376231343735666534353064
          33623463643033623661633732373739316439636663316339346633396338386536366665363234
          37343131306463336630336262363666323762313830323831303162343665616664633631666336
          30376332363334376561313234313536626534633364323662393638316233323637393066383635
          34336337373164333962373165353765646438306461336231383737613834653565333832326532
          623037626533386437643962623638373864

foreman_global_parameters:
  - name: remote_execution_ssh_keys
    parameter_type: array
    value:
      - "{{ foreman_ssh_public_key }}"
  - name: ansible_host_config_key
    value: "{{ awx_host_config_key }}"
  - name: ansible_tower_fqdn
    value: "{{ awx_server_url }}"
  - name: ansible_enabled
    parameter_type: boolean
    value: "True"
  - name: ansible_tower_provisioning
    parameter_type: boolean
    value: "True"
  - name: kernel_params
    parameter_type: string
    value: "console=ttyS1,115200n8 console=tty1 net.ifnames=0 biosdevname=0 nosplash"
  - name: bmc_user
    parameter_type: string
    value: ADMIN
  - name: bmc_password
    parameter_type: string
    value: "{{ foreman.bmc_password }}"


foreman_compute_resources:
  - name: dev01.dev.home.prettybaked.com
    provider: libvirt
    provider_params:
      url: qemu+tcp://10.0.100.100/system
      display_type: vnc

foreman_installation_media:
  - name: CentOS 8 mirror
    os_family: Redhat
    state: absent
  - name: CentOS 9 Stream
    os_family: Redhat
    path: http://mirror.stream.centos.org/$major-stream/BaseOS/$arch/os

foreman_operating_systems:
  - name: "Ubuntu"
    description: "Ubuntu 18.04.3 LTS"
    release_name: "bionic"
    family: "Debian"
    major: "18"
    minor: "04.3"
    provisioning_templates:
      - "Preseed default iPXE"
      - "Preseed default"
      - "Preseed default PXELinux"
      - "Preseed default finish"
      - "Preseed default user data"
    partion_tables:
      - "Preseed default"
      - "Preseed default LVM"
    architectures:
      - x86_64
    media: "Ubuntu mirror"
    parameters:
      - name: additional-packages
        parameter_type: yaml
        value:
          - curl
          - net-tools
          - ethtool
      - name: kernel_params
        parameter_type: string
        value: "console=ttyS1,115200n8 console=tty1 net.ifnames=0 biosdevname=0 nosplash"
      - name: partitioning-type
        parameter_type: string
        value: "general"
      - name: partitioning-recipe
        parameter_type: string
        value: "atomic"
  - name: "Ubuntu"
    description: "Ubuntu 18.04.2 LTS"
    release_name: "bionic"
    family: "Debian"
    major: "18"
    minor: "04.2"
    provisioning_templates:
      - "Preseed default iPXE"
      - "Preseed default"
      - "Preseed default PXELinux"
      - "Preseed default finish"
      - "Preseed default user data"
    partition_tables:
      - "Preseed default"
      - "Preseed default LVM"
    architectures:
      - x86_64
    media: "Ubuntu mirror"
    parameters:
      - name: additional-packages
        parameter_type: yaml
        value:
          - curl
          - net-tools
          - ethtool
      - name: kernel_params
        parameter_type: string
        value: "console=ttyS1,115200n8 console=tty1 net.ifnames=0 biosdevname=0 nosplash"
      - name: partitioning-type
        parameter_type: string
        value: "general"
      - name: partitioning-recipe
        parameter_type: string
        value: "atomic"
  - name: "Ubuntu"
    description: "Ubuntu 18.04"
    release_name: "bionic"
    family: "Debian"
    major: "18"
    minor: "04"
    provisioning_templates:
      - "Preseed default iPXE"
      - "Preseed default"
      - "Preseed default PXELinux"
      - "Preseed default finish"
      - "Preseed default user data"
    partition_tables:
      - "Preseed default"
      - "Preseed default LVM"
    architectures:
      - x86_64
    media: "Ubuntu mirror"
    parameters:
      - name: additional-packages
        parameter_type: yaml
        value:
          - curl
          - net-tools
          - ethtool
      - name: kernel_params
        parameter_type: string
        value: "console=ttyS1,115200n8 console=tty1 net.ifnames=0 biosdevname=0 nosplash"
      - name: partitioning-type
        parameter_type: string
        value: "general"
      - name: partitioning-recipe
        parameter_type: string
        value: "atomic"
  - name: "Ubuntu"
    description: "Ubuntu 20.04"
    release_name: "focal"
    family: "Debian"
    major: "20"
    minor: "04"
    provisioning_templates:
      - "Preseed default iPXE"
      - "Preseed default"
      - "Preseed default PXELinux"
      - "Preseed default finish"
      - "Preseed default user data"
    partion_tables:
      - "Preseed default"
      - "Preseed default LVM"
    architectures:
      - x86_64
    media: "Ubuntu mirror"
    parameters:
      - name: additional-packages
        parameter_type: yaml
        value:
          - curl
          - net-tools
          - ethtool
      - name: kernel_params
        parameter_type: string
        value: "console=ttyS1,115200n8 console=tty1 net.ifnames=0 biosdevname=0 nosplash"
      - name: partitioning-type
        parameter_type: string
        value: "general"
      - name: partitioning-recipe
        parameter_type: string
        value: "atomic"
  - name: "CentOS"
    description: "CentOS 7.7"
    family: "Redhat"
    major: "7"
    minor: "7"
    provisioning_templates:
      - "Kickstart default iPXE"
      - "Kickstart default"
      - "Kickstart default PXELinux"
      - "Kickstart default finish"
      - "Kickstart default user data"
    partion_tables:
      - "Kickstart default"
      - "Kickstart default thin"
    architectures:
      - x86_64
    media: "CentOS 7 mirror"
    parameters:
      - name: additional-packages
        parameter_type: yaml
        value:
          - net-tools
          - redhat-lsb
      - name: autopart_options
        parameter_type: string
        value: "--type=plain --nohome --fstype=ext4"
      - name: kernel_params
        parameter_type: string
        value: "console=ttyS1,115200n8 console=tty1 net.ifnames=0 biosdevname=0"
      - name: selinux-mode
        parameter_type: string
        value: "disabled"
  - name: "CentOS"
    description: "CentOS 8.0"
    family: "Redhat"
    major: "8"
    minor: "0"
    provisioning_templates:
      - "Kickstart default iPXE"
      - "Kickstart default"
      - "Kickstart default PXELinux"
      - "Kickstart default finish"
      - "Kickstart default user data"
    partion_tables:
      - "Kickstart default"
      - "Kickstart default thin"
    architectures:
      - x86_64
    media: "CentOS Stream"
    parameters:
      - name: additional-packages
        parameter_type: yaml
        value:
          - net-tools
          - redhat-lsb
      - name: autopart_options
        parameter_type: string
        value: "--type=plain --nohome --fstype=ext4"
      - name: kernel_params
        parameter_type: string
        value: "console=ttyS1,115200n8 console=tty1 net.ifnames=0 biosdevname=0"
      - name: selinux-mode
        parameter_type: string
        value: "disabled"
  - name: "CentOS"
    description: "CentOS 8.1"
    family: "Redhat"
    major: "8"
    minor: "1"
    provisioning_templates:
      - "Kickstart default iPXE"
      - "Kickstart default"
      - "Kickstart default PXELinux"
      - "Kickstart default finish"
      - "Kickstart default user data"
    partition_tables:
      - "Kickstart default"
      - "Kickstart default thin"
    architectures:
      - x86_64
    media: "CentOS Stream"
    parameters:
      - name: additional-packages
        parameter_type: yaml
        value:
          - net-tools
          - redhat-lsb
      - name: autopart_options
        parameter_type: string
        value: "--type=plain --nohome --fstype=ext4"
      - name: kernel_params
        parameter_type: string
        value: "console=ttyS1,115200n8 console=tty1 net.ifnames=0 biosdevname=0"
      - name: selinux-mode
        parameter_type: string
        value: "disabled"
  - name: "CentOS"
    description: "CentOS Linux release 8.2.2004 (Core)"
    family: "Redhat"
    major: "8"
    minor: "2.2004"
    provisioning_templates:
      - "Kickstart default iPXE"
      - "Kickstart default"
      - "Kickstart default PXELinux"
      - "Kickstart default finish"
      - "Kickstart default user data"
    partition_tables:
      - "Kickstart default"
      - "Kickstart default thin"
    architectures:
      - x86_64
    media: "CentOS Stream"
    parameters:
      - name: additional-packages
        parameter_type: yaml
        value:
          - net-tools
          - redhat-lsb
      - name: autopart_options
        parameter_type: string
        value: "--type=plain --nohome --fstype=ext4"
      - name: kernel_params
        parameter_type: string
        value: "console=ttyS1,115200n8 console=tty1 net.ifnames=0 biosdevname=0"
      - name: selinux-mode
        parameter_type: string
        value: "disabled"
  - name: "CentOS"
    description: "CentOS Linux release 8.4.2105"
    family: "Redhat"
    major: "8"
    minor: "4.2105"
    provisioning_templates:
      - "Kickstart default iPXE"
      - "Kickstart default"
      - "Kickstart default PXELinux"
      - "Kickstart default finish"
      - "Kickstart default user data"
    partition_tables:
      - "Kickstart default"
    architectures:
      - x86_64
    media: "CentOS Stream"
    parameters:
      - name: additional-packages
        parameter_type: yaml
        value:
          - net-tools
          - redhat-lsb
      - name: autopart_options
        parameter_type: string
        value: "--type=plain --nohome --fstype=ext4"
      - name: kernel_params
        parameter_type: string
        value: "console=ttyS1,115200n8 console=tty1 net.ifnames=0 biosdevname=0"
      - name: selinux-mode
        parameter_type: string
        value: "disabled"
  - name: "CentOS"
    description: "CentOS 9"
    family: "Redhat"
    major: "9"
    minor: "0"
    provisioning_templates:
      - "Kickstart default iPXE"
      - "Kickstart default"
      - "Kickstart default PXELinux"
      - "Kickstart default finish"
      - "Kickstart default user data"
    partition_tables:
      - "Kickstart default"
    architectures:
      - x86_64
    media: "CentOS 9 Stream"
    parameters:
      - name: additional-packages
        parameter_type: yaml
        value:
          - net-tools
          - redhat-lsb
      - name: autopart_options
        parameter_type: string
        value: "--type=plain --nohome --fstype=ext4"
      - name: kernel_params
        parameter_type: string
        value: "console=ttyS1,115200n8 console=tty1 net.ifnames=0 biosdevname=0"
      - name: selinux-mode
        parameter_type: string
        value: "disabled"

foreman_system_users:
  - name: foreman
    uid: 998
    gid: 998
    home_dir: /usr/share/foreman
    directories:
      - name: .ssh
        mode: '0755'
        files:
          - source: id_rsa.foreman
            dest: id_rsa
            decrypt: true
            mode: '0600'
          - source: id_rsa.foreman.pub
            dest: id_rsa.pub
            decrypt: true
            mode: '0644'
  - name: foreman-proxy
    uid: 997
    gid: 997
    home_dir: /usr/share/foreman-proxy
    directories:
      - name: .ssh
        mode: '0755'
        files:
          - source: id_rsa_foreman_proxy
            dest: id_rsa_foreman_proxy
            decrypt: true
            mode: '0600'
          - source: id_rsa_foreman_proxy.pub
            dest: id_rsa_foreman_proxy.pub
            decrypt: true
            mode: '0644'

foreman_auth_sources_ldap:
  - name: '{{ ldap_authentication.server }}'
    host: '{{ ldap_authentication.host }}'
    port: '{{ ldap_authentication.server_port }}'
    tls: '{{ ldap_authentication.server_tls }}'
    onthefly_register: true
    server_type: posix
    account: '{{ ldap_authentication.account_dn }}'
    account_password: '{{ ldap_authentication.account_password }}'
    base_dn: '{{ ldap_authentication.base_dn }}'
    groups_base: '{{ ldap_authentication.groups_base }}'
    attr_login: '{{ ldap_authentication.attr_login }}'
    attr_firstname: '{{ ldap_authentication.attr_firstname }}'
    attr_lastname: '{{ ldap_authentication.attr_lastname }}'
    attr_mail: '{{ ldap_authentication.attr_mail }}'
    ldap_filter: (&(objectClass=posixAccount)(|(gidNumber=1042)(gidNumber=2002)))
    locations: '{{ foreman_location }}'
    usergroup_sync: true
