---

- name: Configure Foreman
  gather_facts: true
  hosts:
    - foreman

  tasks:
    - name: Configure Foreman Settings
      ansible.builtin.include_role:
        name: theforeman.foreman.settings

    - name: Configure Foreman LDAP Authentication Sources
      ansible.builtin.include_role:
        name: theforeman.foreman.auth_sources_ldap

    - name: Configure Foreman Usergroups
      theforeman.foreman.usergroup:
        name: '{{ usergroup.name }}'
        admin: '{{ usergroup.admin | default(False) }}'
        roles: '{{ usergroup.roles | default(omit) }}'
        users: '{{ usergroup.users | default(omit) }}'
        usergroups: '{{ usergroups.usergroups | default(omit) }}'
        server_url: '{{ foreman_server_url }}'
        username: '{{ foreman_username }}'
        password: '{{ foreman_password }}'
        state: '{{ usergroup.state | default("present") }}'
        validate_certs: false
      loop: '{{ foreman_usergroups.internal }}'
      loop_control:
        loop_var: usergroup
        label: '{{ usergroup.name }}'

    - name: Configure Foreman External Usergroups
      theforeman.foreman.external_usergroup:
        name: '{{ usergroup.name }}'
        auth_source_ldap: '{{ usergroup.auth_source }}'
        usergroup: '{{ usergroup.usergroup }}'
        server_url: '{{ foreman_server_url }}'
        username: '{{ foreman_username }}'
        password: '{{ foreman_password }}'
        state: '{{ usergroup.state | default("present") }}'
        validate_certs: false
      loop: '{{ foreman_usergroups.external }}'
      loop_control:
        loop_var: usergroup
        label: '{{ usergroup.name }}'
