---

- name: Configure Foreman
  gather_facts: true
  hosts:
    - foreman
  roles:
#    - name: theforeman.foreman.settings
    - name: theforeman.foreman.auth_sources_ldap
      vars:
        foreman_auth_sources_ldap:
          - name: PrettyBaked LDAP
            host: '{{ ldap_authentication.host }}'
            port: 389
            tls: false
            onthefly_register: true
            server_type: posix
            account: '{{ ldap_authentication.account }}'
            account_password: '{{ ldap_authentication.account_password}}'
            base_dn: '{{ ldap_authentication.base_dn }}'
            groups_base: '{{ ldap_authentication.groups_base }}'
            attr_login: '{{ ldap_authentication.attr_login }}'
            attr_firstname: '{{ ldap_authentication.attr_firstname }}'
            attr_lastname: '{{ ldap_authentication.attr_lastname }}'
            attr_mail: '{{ ldap_authentication.attr_mail }}'
            ldap_filter: (&(objectClass=posixAccount)(|(gidNumber=1042)(gidNumber=2002)))
            locations: '{{ foreman_location }}'
            usergroup_sync: true
            state: present
