---

- name: Install Foreman
  gather_facts: true
  hosts:
    - foreman
  vars:
    foreman_installer_options: "{{ ([''] + foreman_options) | join(' --') | split(' ') | reject('eq', '') | list }}"
  roles:
    - name: theforeman.operations.foreman_repositories
    - name: theforeman.operations.ansible_repositories
      when:
        - ansible_os_family|lower != 'debian'
    - name: theforeman.operations.puppet_repositories
    - name: theforeman.operations.installer
