---

- name: Foreman Prerequisites
  gather_facts: true
  hosts:
    - foreman

  tasks:
    - name: Create foreman group
      ansible.builtin.group:
        name: foreman
        gid: 998
        state: present

    - name: Create foreman-proxy group
      ansible.builtin.group:
        name: foreman-proxy
        gid: 997
        state: present

    - name: Create foreman user
      ansible.builtin.user:
        name: foreman
        uid: 998
        group: foreman
        create_home: true
        state: present

    - name: Create foreman-proxy user
      ansible.builtin.user:
        name: foreman-proxy
        uid: 997
        group: foreman-proxy
        create_home: true
        state: present

    - name: Create foreman-proxy group
      ansible.builtin.group:
        name: foreman-proxy
        gid: 997
        state: present

    - name: Create foreman-proxy user ssh directory
      ansible.builtin.file:
        path: /var/lib/foreman-proxy/ssh
        state: directory
        owner: foreman-proxy
        group: foreman-proxy
        mode: 0755

    - name: Copy foreman-proxy ssh credentials
      ansible.builtin.copy:
        dest: '/var/lib/foreman-proxy/ssh/{{ item }}'
        src: '{{ item }}'
        decrypt: true
        owner: foreman-proxy
        group: foreman-proxy
      loop:
        - id_rsa_foreman_proxy
        - id_rsa_foreman_proxy.pub

- name: Install Foreman
  gather_facts: true
  hosts:
    - foreman
  vars:
    foreman_installer_options: "{{ ([''] + foreman_options) | join(' --') | split(' ') | reject('eq', '') | list }}"
  roles:
    - name: theforeman.operations.foreman_repositories
    - name: theforeman.operations.ansible_repositories
      when:
        - ansible_os_family|lower != 'debian'
    - name: theforeman.operations.puppet_repositories
    - name: theforeman.operations.installer
