---

- name: Foreman Install/Configure
  gather_facts: true
  remote_user: root
  hosts:
    - awx
  tasks:
    - name: Install Foreman
      block:
        - name: Ensure Foreman user/group/directories/files exist
          ansible.builtin.include_tasks:
            file: tasks/foreman_user_groups.yml
          loop: '{{ foreman_users_groups }}'
          loop_control:
            loop_var: foreman_user_group
            label: '{{ foreman_user_group.name }}'
        - name: Add Foreman Repositories
          ansible.builtin.include_role:
            name: theforeman.operations.foreman_repositories
        - name: Add Ansible Repositories
          ansible.builtin.include_role:
            name: theforeman.operations.ansible_repositories
          when:
            - ansible_os_family | lower != 'debian'
        - name: Add Puppet Repositories
          ansible.builtin.include_role:
            name: theforeman.operations.puppet_repositories
        - name: Install Foreman
          ansible.builtin.include_role:
            name: theforeman.operations.installer
          vars:
            update_cache: true
            foreman_installer_options: "{{ ([''] + foreman_options) | join(' --') | split(' ') | reject('eq', '') | list }}"
      tags:
        - install-foreman

    - name: Configure Foreman
      block:
        - name: "Update global parameters"
          theforeman.foreman.global_parameter:
            name: "{{ item.name }}"
            value: "{{ item.value }}"
            parameter_type: "{{ item.parameter_type | default('string') }}"
            server_url: '{{ foreman_server_url }}'
            username: '{{ foreman_username }}'
            password: '{{ foreman_password }}'
            validate_certs: false
            state: present
          loop: '{{ foreman_global_parameters }}'
          loop_control:
            label: '{{ item.name }}: {{ item.value }}'

        - name: Configure Foreman Settings
          ansible.builtin.include_role:
            name: theforeman.foreman.settings

        - name: Configure Foreman LDAP Authentication Sources
          ansible.builtin.include_role:
            name: theforeman.foreman.auth_sources_ldap

        - name: Configure Foreman Usergroups
          theforeman.foreman.usergroup:
            name: '{{ usergroup.name }}'
            admin: '{{ usergroup.admin | default(False) }}'
            roles: '{{ usergroup.roles | default(omit) }}'
            users: '{{ usergroup.users | default(omit) }}'
            usergroups: '{{ usergroups.usergroups | default(omit) }}'
            server_url: '{{ foreman_server_url }}'
            username: '{{ foreman_username }}'
            password: '{{ foreman_password }}'
            state: '{{ usergroup.state | default("present") }}'
            validate_certs: false
          loop: '{{ foreman_usergroups.internal }}'
          loop_control:
            loop_var: usergroup
            label: '{{ usergroup.name }}'

        - name: Configure Foreman External Usergroups
          theforeman.foreman.external_usergroup:
            name: '{{ usergroup.name }}'
            auth_source_ldap: '{{ usergroup.auth_source }}'
            usergroup: '{{ usergroup.usergroup }}'
            server_url: '{{ foreman_server_url }}'
            username: '{{ foreman_username }}'
            password: '{{ foreman_password }}'
            state: '{{ usergroup.state | default("present") }}'
            validate_certs: false
          loop: '{{ foreman_usergroups.external }}'
          loop_control:
            loop_var: usergroup
            label: '{{ usergroup.name }}'
      tags:
        - configure-foreman
